linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - misspell
    - gocyclo
    - gosec
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G404  # Use of weak random number generator

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

run:
  deadline: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
